### ISSUE TITLE
When open source code！

### ISSUE THREAD

**Issue by hu-jerry** [oskarnatan/end-to-end-driving#1]
Thanks youy great work, when open source code?

**Comment by oskarnatan** [comment]
Hello, thanks for asking.

The manuscript has just got accepted recently. I am planning to tidy up and upload the code within the next month. Stay tuned.

**Comment by oskarnatan** [comment]
Hello there, I have uploaded all the necessary codes!
Only the download link for the dataset is left behind, but you can generate the dataset by yourself.
